On premise logging with Loki
RosemanLabs/helm-charts pull request #16
Opened 2024-08-16 13:38 UTC by matthijswolters-rl

This PR is a solution for [this issue ticket](https://github.com/RosemanLabs/RL-Development/issues/817). It contains quite a number of changes:
- Grafana Alloy is deployed as a sidecar to the engine pods
- Grafana Loki and Grafana are deployed as extra pods and included in the VPN. It follows that VPN must be enabled for the logging stack to work, which is checked in `deploy_single_node.sh`.
- A preconfigured dashboard is included that shows an overview of the logs of each of the nodes.
- The README has been updated to include instructions for deploying the logging stack
- The deployment script has been updated to make it easy to deploy the logging stack

One thing that we will have to find out in practice is how quickly the Loki disk gets full. The disk is 10Gi in size, so I would assume that should be sufficient for quite a while. It is also good to note that the logs live on the loki PVC so that even if the Loki pod is killed, the logs are still readable.

2024-08-19 09:33 UTC, robinderooij-rl requested changes

2024-08-19 09:33 UTC, robinderooij-rl commented on scripts/deploy_single_node.sh
> +#helm template vdl "${install_params[@]}"
Can you remove this one?

2024-08-19 09:33 UTC, robinderooij-rl commented on charts/vdl/values.yaml
> +          memory: 100Mi # TODO: check if this is reasonable
This seems reasonable

2024-08-19 09:33 UTC, robinderooij-rl commented on charts/vdl/templates/alloy_clusterrole.yaml
> +  resources:
Can we check whether we want all these resources for our use case?

2024-08-19 09:33 UTC, robinderooij-rl commented on README.md
> +  2. If your deployment contains either node1 or node2 then you must include the following override settings. Furthermore, it is important to deploy this chart into a namespace with a unique name, ot
Alternative config instructions when an existing deployment already has the same namespace for different nodes?

2024-08-26 07:42 UTC, tomhemmes-rl requested changes

2024-08-26 07:42 UTC, tomhemmes-rl commented on charts/vdl/values.yaml
> +  node1Namespace: ""
The naming here (e.g. "node1") that depends on which node you're installing right? Elsewhere in the values they are referred to as peerA and peerB.

2024-08-26 07:42 UTC, tomhemmes-rl commented on charts/vdl/templates/alloy_config.yaml
Do we need configuration for node logs too?

2024-08-26 07:42 UTC, tomhemmes-rl commented on charts/vdl/values.yaml
> +      image: "alpine:3.12"
@robinderooij-rl what are your thoughts about using public images here instead of our mirrors?

2024-08-27 09:58 UTC, matthijswolters-rl commented on charts/vdl/values.yaml
> +  node1Namespace: ""
In the override values they are referred to as peerA and peerB because the engine node is agnostic on which outgoing connections it can define, however the concept of a node number is definitely something that is defined in the values as well, see `core.nodeNr`

2024-08-27 09:59 UTC, matthijswolters-rl commented on charts/vdl/templates/alloy_config.yaml
I don't know, what do @rrooij and @hugoideler think? Maybe we can add those in another iteration.

2024-08-27 09:59 UTC, matthijswolters-rl commented on README.md
> +  2. If your deployment contains either node1 or node2 then you must include the following override settings. Furthermore, it is important to deploy this chart into a namespace with a unique name, ot
I have updated the flow to make use of the static label rather than expecting the namespace name to be unique. I think that makes more sense given the current set up

2024-08-27 12:13 UTC, tomhemmes-rl requested changes

2024-08-27 12:57 UTC, matthijswolters-rl commented on charts/vdl/values.yaml
> +  lokiEndpoint: __FILL_IN_VPN_IP_HERE__:3100/loki/api/v1/push
I'm not really sure I can set a sensible default for this value. I have also seen `values.yaml` used as a reference for what values to include in some override. I can turn this into a comment and leave the default value empty?

2024-08-28 14:47 UTC, matthijswolters-rl commented on charts/vdl/templates/alloy_config.yaml
I suggest we add this in another iteration, if it becomes clear that we need those logs

2024-09-04 07:46 UTC, tomhemmes-rl requested changes

2024-09-04 07:46 UTC, tomhemmes-rl commented on charts/vdl/values.yaml
> +# loggingEnabled: if enabled, will create a Grafana Alloy sidecar. NOTE: vpnEnabled must be true for this setup to work
Can we add validation to make sure vpnEnabled is indeed set to true, except someone needing to debug and then finding this comment?

2024-09-10 08:32 UTC, robinderooij-rl approved these changes

2024-09-10 08:33 UTC, merged