Add external dns annotations
RosemanLabs/helm-charts pull request #17
Opened 2024-08-30 15:00 UTC by matthijswolters-rl

Adds annotations to allow external-dns operator to create DNS records. Based on my conversation with @tomhemmes-rl this PR assumes that external-dns has already been deployed to the cluster.

2024-09-09 11:40 UTC, tomhemmes-rl requested changes

2024-09-09 11:40 UTC, tomhemmes-rl commented on charts/vdl/values.yaml
> +  enabled: true
Why did you make this enabled by default?

2024-09-09 11:40 UTC, tomhemmes-rl commented on charts/vdl/values.yaml
> +  target: "" # Fill in LoadBalancer or Reverse-Proxy IP in here
Could you make these required when enabled=true?

2024-09-10 09:37 UTC, matthijswolters-rl commented on charts/vdl/values.yaml
> +  enabled: true
Fair point, I just assumed this would be the preferred deployment method

2024-09-10 11:53 UTC, tomhemmes-rl approved these changes

2024-09-10 11:57 UTC, merged