docker rootless support and bugfixes
RosemanLabs/helm-charts pull request #19
Opened 2024-09-12 11:50 UTC by hugoideler-rl

- This PR supports rootless mode by means of an init container that sets permissions to user 1000:1000. This logic should be replicated in the Terraform code. This logic should be forward-compatible in case older releases are deployed, since the root user can access files owned by 1000:1000 just fine.
- This PR includes a bugfix for running the Helm-chart without logging enabled.

2024-09-12 12:57 UTC, tomhemmes-rl commented on charts/vdl/templates/statefulset.yaml
> +        - name: vdl-permissions-setup
Since this is only relevant once wouldn't it make more sense to run this as a Helm pre-upgrade hook job?
https://helm.sh/docs/topics/charts_hooks/

2024-09-12 14:25 UTC, hugoideler-rl commented on charts/vdl/templates/statefulset.yaml
> +        - name: vdl-permissions-setup
Interesting idea, but I'm not sure if it's only on an upgrade. When you attach a fresh PVC, it tends to be initialized as root:root with 755, no? In the past that was not a problem, but it may be now.

Diving a little more into this, the proper k8s way may actually be using a `securityContext`. [Docs](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods).

> By default, Kubernetes recursively changes ownership and permissions for the contents of each volume to match the fsGroup specified in a Pod's securityContext when that volume is mounted.

Hmm, perhaps this initContainer becomes redundant altogether if we start to use `securityContext`. Athough it's basically doing the same, it may be the nicer solution. To be investigated.

Another caveat if we go that route:

> The security settings that you specify for a Pod apply to all Containers in the Pod.

2024-09-16 20:18 UTC, hugoideler-rl commented on charts/vdl/templates/statefulset.yaml
> +        - name: vdl-permissions-setup
I've now pushed a new commit:
- This one adds the use of `SecurityContext`. The `SecurityContext` has an `fsgroup` which will `chgrp` all PVCs mounted, however, it does not `chown` them. This means that files previously created by `root` will still not be writeable by our non-root user. However, any new files created will have the right UID:GID going forward (so for a new deployment, that means all files).
- The question that then remains, is this 'file permission fixer' `initContainer` that I added something to run every time, or as part of a Helm hook?
  - Pro of Helm hook is that we don't run it more often than needed (although k8s' `fsgroup` also does basically the same as am my operation at every pod start, which k8s acknowledges is not ideal but acceptable unless you have huge amount of files)
  - Con of Helm hook is that I'm not sure if we can be 100% certain it will always cover our migrations? If for whatever reason it doesn't get run, it would be a total blocker for that deployment. Edge cases could be: an old env moving to Helm (I presume update hook is not run then), Helm chart being killed before update hook has finished, ... I've struggled with flaky Helm deployments in the past (around complex ElasticSearch chart) where hooks sometimes hang and I had to kill them, but this is just n=1 and to blame on that ES Helm chart. Happy to follow your guidance on the Helm hook.

As a bonus:
- This branch now also makes the docker image read-only. That also means no more on-the-fly `microdnf`, but we use ephemeral debug containers for that anyway nowadays.

2024-09-17 14:19 UTC, hugoideler-rl commented
I tested this branch on a fresh deployment and one that carried over files with root:root ownership.

2024-09-17 14:27 UTC, tomhemmes-rl commented on charts/vdl/templates/statefulset.yaml
> +        - name: vdl-permissions-setup
Gotcha, in that case I think the risks are to great compared to the cost of running it as an initContainer. Lets do it your way until it becomes too slow :+1:

2024-09-17 14:28 UTC, tomhemmes-rl approved these changes

2024-09-17 14:29 UTC, robinderooij-rl approved these changes

2024-09-17 14:30 UTC, robinderooij-rl requested changes

2024-09-17 14:30 UTC, robinderooij-rl commented on charts/vdl/templates/statefulset.yaml
> +          image: apteno/alpine-jq
An image SHA would be the best

2024-09-20 13:38 UTC, hugoideler-rl commented
The latest commit now makes the images independent of 3rd party hosting and pins the versions as much as possible

2024-09-20 14:04 UTC, robinderooij-rl approved these changes

2024-09-22 15:00 UTC, merged